NAME = phonebook

FLAGS = -Wall -Wextra -Werror -std=c++98

CC = c++

all: $(NAME)
$(NAME): PhoneBook.cpp
		@$(CC) $(FLAGS) PhoneBook.cpp -o $(NAME)
clean : 
	rm $(NAME)
fclean :
	rm $(NAME)
re :clean all